### ISSUE TITLE
The +- combined character doesn't display when I run Physicalc in a bash shell

### ISSUE THREAD

**Issue by SarahHand** [J9465812/PhysiCalc#11]
I've run PhysiCalc in the git bash shell and the combined +- character doesn't display properly. 

A suggestion for handling this would be when the program starts, display the combined +- character to the user and have him/her confirm that it displayed properly. If not, switch to using "+-".

Alternatively, perhaps add a configuration file to PhysiCalc that defines how that symbol is displayed and then a mechanism for the user to provide his/her own configuration file or to override those configured items.

I'm using git-bash on Windows-10 (mintty 3.1.0) as my bash shell and I discovered a way to get the combined +- character to display properly. Using the context menu in git-bash, right click and select "Options". Go to the "Text" tab and set the Character Set to "CP 1252". After doing this, the combined +- character displayed properly.  

Perhaps include these details on the Wiki or a Troubleshooting page/help command.

**Comment by J9465812** [comment]
It turns out this is also an issue in the command window, so I'll remove the character entirely in the next update.

**Comment by J9465812** [comment]
I've fixed this issue in Version 1.1.1
